version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/react-cmp"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"