[tools]
node = '24'
prek = '0.3'
editorconfig-checker = '3'
shfmt = '3'
shellcheck = '0.11'

[env]
DOCKER_IMAGE_NAME = "simonbriche/simonbriche-personal-website"
DOCKER_REGISTRY = "ghcr.io"
DOCKER_HOST_PORT = "3000"
DOCKER_CONTAINER_PORT = "3000"

[tasks."server"]
description = "Run the server"
run = "cd src/server && nf start"

[tasks."server:build"]
description = "Build the server to be ready for production"
depends = [
  "react:build"
]
run = "echo 'server is ready to be deployed to production'"

[tasks."react:build"]
description = "Build the React components"
usage = '''
flag "--dev" help="Build for development" default=#false
'''
run = '''
  #!/usr/bin/env bash
  set -euo pipefail

  echo "Building frontend for development"
  # if [[ "${dev}" == "true" ]]; then
  #   npm run build:development --prefix src/react-cmp
  # else
  #   npm run build --prefix src/react-cmp
  # fi
  echo "Frontend is built"
'''

# Docker related tasks
[tasks."docker:full-image-name"]
description = "Print the full image name."
usage = '''
arg "<image_name>" help="Name of the Docker image to build" env="DOCKER_IMAGE_NAME"
flag "-r --registry <registry>" help="Name of the Docker registry to push the image" env="DOCKER_REGISTRY"
flag "-t --tag <tag>" help="Tag to apply to the built image" default=""
'''
run = '''
  #!/usr/bin/env bash
  set -euo pipefail

  if [[ -n "${usage_tag}" ]]; then
    full_image_ref="${usage_registry}/${usage_image_name}:${usage_tag}"
  else
    full_image_ref="${usage_registry}/${usage_image_name}:$(git rev-parse --short HEAD)"
  fi
  echo "${full_image_ref}"
'''

[tasks."docker:build"]
description = "Build the Docker image for the server"
usage = '''
arg "<image_name>" help="Name of the Docker image to build" env="DOCKER_IMAGE_NAME"
flag "-r --registry <registry>" help="Name of the Docker registry to push the image" env="DOCKER_REGISTRY"
flag "-t --tag <tag>" help="Tag to apply to the built image" default=""
flag "-f --file <file>" help="Path to the Dockerfile" default="Dockerfile"
flag "-x --extra-arg <extra_arg>" var=#true help="Extra args to pass to the docker build command" env="DOCKER_EXTRA_ARGS"
'''
run = '''
  #!/usr/bin/env bash
  set -xeuo pipefail

  if [ -n "${usage_extra_arg}" ]; then
    usage_extra_arg+=(${usage_extra_arg})
  fi

  printf "Extra arg [%s]\n" "${usage_extra_arg[@]}"

  full_image_ref="$(mise run docker:full-image-name "${usage_image_name}" --registry "${usage_registry}" --tag "${usage_tag}")"
  echo "Building Docker image with ${usage_file}..."
  echo "Full image name: ${full_image_ref}"
  docker buildx build ${usage_extra_arg[@]} \
    -f "${usage_file}" \
    -t "${full_image_ref}" \
    --build-arg ARG_DOCKER_BASE_IMAGE_NAME=node \
    --build-arg ARG_DOCKER_BASE_IMAGE_VERSION=24-alpine \
    .

  echo "Docker image built successfully"
'''

[tasks."docker:push"]
description = "Push the Docker image to the registry"
wait_for = ["docker:build"]
usage = '''
arg "<image_name>" help="Name of the Docker image to build" env="DOCKER_IMAGE_NAME"
flag "-r --registry <registry>" help="Name of the Docker registry to push the image" env="DOCKER_REGISTRY"
flag "-t --tag <tag>" help="Tag to apply to the built image" default=""
'''
run = '''
  #!/usr/bin/env bash
  set -xeuo pipefail

  full_image_ref="$(mise run docker:full-image-name "${usage_image_name}" --registry "${usage_registry}" --tag "${usage_tag}")"
  echo "Pushing Docker image to ${full_image_ref}..."
  docker push "${full_image_ref}"
  echo "Docker image pushed successfully"
'''

[tasks."docker:run"]
description = "Run the Docker image"
usage = '''
arg "<image_name>" help="Name of the Docker image to build" env="DOCKER_IMAGE_NAME"
flag "-p --port <port>" help="Port to expose for the host" env="DOCKER_HOST_PORT"
flag "--container-port <container_port>" help="Port to expose for the Docker container" env="DOCKER_CONTAINER_PORT"
flag "-r --registry <registry>" help="Name of the Docker registry to get the image from" env="DOCKER_REGISTRY"
flag "-t --tag <tag>" help="Tag to apply to the built image" default=""
'''
run = '''
  #!/usr/bin/env bash
  set -euo pipefail

  full_image_ref="$(mise run docker:full-image-name "${usage_image_name}" --registry "${usage_registry}" --tag "${usage_tag}")"
  echo "Running Docker image ${full_image_ref}..."
  docker container run \
    -ti \
    -p${usage_port}:${usage_container_port} \
    --rm \
      ${full_image_ref}
'''

[tasks.docker]
description = "Full build and push of the Docker image registry"
depends = [
  { task = "docker:build", args = [
    "{{usage.image_name}}",
    "--registry", "{{usage.registry}}",
    "--tag", "{{usage.tag}}",
    "--file", "{{usage.file}}"
  ] },
  { task = "docker:push", args = [
    "{{usage.image_name}}",
    "--registry", "{{usage.registry}}",
    "--tag", "{{usage.tag}}"
  ] }
]
usage = '''
arg "<image_name>" help="Name of the Docker image to push" env="DOCKER_IMAGE_NAME"
flag "-r --registry <registry>" help="Name of the Docker registry to push the image" env="DOCKER_REGISTRY"
flag "-t --tag <tag>" help="Tag to apply to the built image" default=""
flag "-f --file <file>" help="Path to the Dockerfile" default="Dockerfile"
'''
run = "echo 'Docker image built and pushed successfully'"
