---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace
        exclude: |
          (?x)^(
              ^public/tarteaucitron/.*|
              ^public/assets/webfonts/.*|
              ^public/react-cmp/production/.*|
              ^dev/.*|
              ^keys/.*|
          )$
      - id: check-yaml # Validates YAML files
        args: [--allow-multiple-documents]
      - id: check-toml # Validates TOML files
      - id: check-json # Validates JSON files # .vscode/ json files are actually jsonc files
        exclude: |
          (?x)^(
              ^.vscode/.*
          )$
      - id: check-xml # Validates XML files
      - id: check-added-large-files # Checks for files that are added to the repository that are larger than a threshold
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Checks for files that contain merge conflict strings
        args: [--assume-in-merge]
      - id: detect-private-key # Check for the existence of private keys
        exclude: |
          (?x)^(
              ^keys/.*
          )$
      - id: check-executables-have-shebangs # Checks that executables have shebangs
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
        exclude: |
          (?x)^(
              .gitmodules|
              ^public/tarteaucitron/.*|
              ^public/assets/webfonts/.*|
              ^public/react-cmp/production/.*|
              ^dev/.*|
              ^keys/.*|
          )$

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker-system # Check editorconfig compliance
        alias: ec

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        pass_filenames: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck # Shell scripts conform to shellcheck
      - id: shfmt # Check shell style with shfmt

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--no-warnings]
        exclude: |
          (?x)^(
              .pre-commit-config.yaml
          )$

  - repo: https://github.com/looztra/yamkix
    rev: v0.13.0
    hooks:
      - id: yamkix
        name: yamkix (global)
        args: [--no-quotes-preserved]

  - repo: local
    hooks:
      - id: app-prettier
        name: Run prettier
        language: system
        files: ^.*$
        types_or: [javascript, json]
        require_serial: true
        entry: |
          bash -c 'if [[ "$CI" = "true" ]]; then npm run lint:prettier; else npm run fix:prettier; fi' --
          bash -c 'if [[ "$CI" = "true" ]]; then npm --prefix react-cmp/src run lint:prettier; else npm --prefix react-cmp/src run fix:prettier; fi' --
