# ************************************************************
# Sequel Ace SQL dump
# Version 3038
#
# https://sequel-ace.com/
# https://github.com/Sequel-Ace/Sequel-Ace
#
# Host: 127.0.0.1 (MySQL 8.0.19)
# Database: website
# Generation Time: 2021-11-08 15:32:31 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
SET NAMES utf8mb4;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE='NO_AUTO_VALUE_ON_ZERO', SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table portfolio
# ------------------------------------------------------------

DROP TABLE IF EXISTS `portfolio`;

CREATE TABLE `portfolio` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` binary(16) DEFAULT NULL,
  `client` varchar(255) DEFAULT NULL,
  `types` json DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `pitch` text,
  `trivia` text,
  `technology_ids` json DEFAULT NULL,
  `thumbnail` varchar(255) DEFAULT NULL,
  `images` json DEFAULT NULL,
  `section` enum('sixpans','featured','perso') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `priority` int unsigned DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOCK TABLES `portfolio` WRITE;
/*!40000 ALTER TABLE `portfolio` DISABLE KEYS */;

INSERT INTO `portfolio` (`id`, `uuid`, `client`, `types`, `name`, `description`, `pitch`, `trivia`, `technology_ids`, `thumbnail`, `images`, `section`, `priority`, `created_at`)
VALUES
	(1,X'11EC334E1DBEDF48B4DF25E613AA1F9A','Pierre&Vacances','[\"Website\", \"Twitter bot\"]','La Carte postale à un inconnu','<p>L\'idée de départ de cette application était de générer du contenu par la communauté pour la communauté. Nous avaons donc fusionné deux mécaniques : le concours photo et la réponse automatique Twitter, la base de l\'une enrichissant la base de l\'autre.</p>','Un mini-site dédié permettait d\'uploader une photo (ou d\'en choisir une parmi une sélection), puis d\'écrire un message qui va l’accompagner. Une “Carte postale” était ainsi générée à partir de ces informations. Ensuite, chaque tweet comprenant le hashtag #LesVacancesCommeMoi et recevait une réponse automatique avec une des cartes générées sur le site.',NULL,'[1, 2, 3, 4, 5, 6, 7]','pvcp-carte_postale-thumbnail.png','[\"pvcp-carte_postale-desktop-1.png\", \"pvcp-carte_postale-ar.png\"]','featured',4,'2021-07-27 11:57:07'),
	(2,X'11EC334E1DBF4A5AB4DF25E613AA1F9A','LaSmeno','[\"Website\"]','Où est Maya ?',NULL,'Via une application web intégrée en iFrame sur le site de LaSmeno, ce jeu concours permettait aux internautes de deviner où était prise la photo affichée en posant un marker sur une Map Google. A la validation, la distance était affichée et un tirage au sort parmi les joueurs les plus près était fait pour déterminer les gagnants. 8 destinations étaient à trouver au total.',NULL,'[1, 2, 3, 4, 5, 6, 7]','smeno-ou_est_maya-thumbnail.png','[\"smeno-ou_est_maya-desktop-1.png\"]',NULL,NULL,'2021-07-27 12:36:39'),
	(3,X'11EC334E1DBF51BCB4DF25E613AA1F9A','Sixt','[\"Twitter Bot\"]','SixtBoostYourself',NULL,'Envoie #BOOSTYOURSELF + @SixtFR + #MOT_CLE et reçois immédiatement un message d’encouragement marrant suivant le mot-clé envoyé. Un lien vers une vidéo est également envoyée dans la réponse.',NULL,'[1, 2]','sixt-boost_yourself-thumbnail.png','[\"sixt-boost_yourself-1.png\", \"sixt-boost_yourself-2.png\", \"sixt-boost_yourself-3.png\", \"sixt-boost_yourself-4.png\"]',NULL,NULL,'2021-07-27 12:38:20'),
	(4,X'11EC334E1DBF545AB4DF25E613AA1F9A','Pierre&Vacances','[\"Website\"]','Social Winter',NULL,'Via un mini-site dédié, inscris-toi et poste ta photo de vacances à la montagne en fonction de 3 catégories (famille, amis, enfants). Ta photo apparaît sur la homePage dans une battle de 2 photos. Les utilisateurs votent pour l’une ou l’autre, et un autre couple de photo apparaît. Les photos les plus votées gagnent. Parallèlement à cela, des énigmes sont disponibles pour gagner d’autres lots.',NULL,'[1, 2, 3, 4, 5, 6, 7]','pvcp-social_winter-thumbnail.png','[\"pvcp-social_winter-desktop-1.png\", \"pvcp-social_winter-desktop-2.png\", \"pvcp-social_winter-desktop-3.png\"]',NULL,NULL,'2021-07-27 14:42:21'),
	(5,X'11EC334E1DBF55F4B4DF25E613AA1F9A','Pierre&Vacances','[\"Twitter Bot\"]','CetEteJeChoisisDe',NULL,'Envoie #CetEteJeChoisisDe + @Pierre_vacances + mention d’un ami et reçois immédiatement une idée d’activité avec la personne mentionnée (fonctionne avec 2 ou 3 mentions).',NULL,'[1, 2]','pvcp-cet_ete-thumbnail.png','[\"pvcp-cet_ete-ar.png\"]',NULL,NULL,'2021-07-27 14:44:39'),
	(6,X'11EC334E1DBF5720B4DF25E613AA1F9A','Pumpkin','[\"Website\"]','Site Pumpkin',NULL,'Le site institutionnel de Pumpkin, le paiement entre potes.',NULL,'[1, 2, 3, 4, 5, 6, 8]','pumpkin-site-thumbnail.png','[\"pumpkin-site-desktop-1.png\", \"pumpkin-site-desktop-2.png\"]',NULL,NULL,'2021-07-27 14:45:54'),
	(7,X'11EC334E1DBF5856B4DF25E613AA1F9A','OP1C','[\"Objet connecté\"]','TweetPrint','<p>Il s\'agit ici d\'un dispositif événementiel visant à créer une expérience interactive avec l\'utilisateur. Le principe de base étant qu\'une imprimante est \"connectée\" à un serveur, il peut lui envoyer ce qu\'il souhaite à imprimer à destination de l\'utilisateur. L\'interaction peut donc se faire avec n\'importe quel service en ligne (un Bot Messenger, un Tweet, un #hashtag Instagram) du moment que l\'information peut être reçue instantanément.</p>\n<p>Selon l\'interface, l\'image imprimée peut alors contenir des informations personnalisées : une image de profil Facebook, un viseul déterminé par une discussion avec le Bot, etc...</p>','Imprimante connectée pouvant se piloter avec un Bot Messenger ou un tweet.',NULL,'[1, 2, 3]','op1c-tweet_print-thumbnail.png','[\"op1c-tweet_print-1.png\", \"op1c-tweet_print-2.png\", \"op1c-tweet_print-3.png\", \"op1c-tweet_print-4.png\"]','featured',5,'2021-07-27 14:47:43'),
	(8,X'11EC334E1DBF6E4AB4DF25E613AA1F9A','OP1C','[\"Objet connecté\"]','TweetCoffee',NULL,NULL,NULL,'[1, 2, 3]','op1c-tweet_coffee-thumbnail.png','[\"op1c-tweet_coffee-1.png\", \"op1c-tweet_coffee-2.png\", \"op1c-tweet_coffee-3.png\", \"op1c-tweet_coffee-4.png\", \"op1c-tweet_coffee-5.png\", \"op1c-tweet_coffee-6.png\"]',NULL,NULL,'2021-07-27 14:50:52'),
	(9,X'11EC334E1DBF6FBCB4DF25E613AA1F9A','Norauto','[\"Website\"]','SocialWall',NULL,'Sur plusieurs écrans sont regroupés les KPIs et feed des différents réseaux sociaux de Norauto : Facebook Instagram, Twitter, Youtube, GoogleAnalytics e-commerce.',NULL,'[1, 2, 3, 4, 5, 6, 8]','norauto-socialwall-thumbnail.png','[\"norauto-socialwall-1.png\", \"norauto-socialwall-2.png\", \"norauto-socialwall-3.png\", \"norauto-socialwall-4.png\"]',NULL,NULL,'2021-07-27 14:52:30'),
	(10,X'11EC334E1DBF70F2B4DF25E613AA1F9A','La Mie Câline','[\"Website\"]','Les Trolls chez La Mie Câline','<p>Le principe est simple : connecte-toi via Facebook et choisis une part de galette parmi toutes les galettes de la gamme La Mie Câline. S’il y a une fève dans ta part, tu as gagné ! Si tu as 2 fèves, tu as gagné le gros lot !</p>\n<p>Outre la découverte de la gamme, l\'idée était de rendre l\'application assez dynamique. Mon choix s\'est porté sur l\'intégration d\'animation faites avec <a href=\"https://airbnb.design/lottie/\" target=\"_blank\" ref=\"noopener\">Lottie</a>, qui permet d\'exporter des animations After Effects vers le web. Quelques particules ont aussi été ajoutées pour un effet  \"féérique\".</p>','Jeu en Instant Gagnant via un mini-site dédié pour La Mie Câline.',NULL,'[1, 2, 3, 4, 5, 6, 7]','lmc-trolls-thumbnail.png','[\"lmc-trolls-mobile-1.png\", \"lmc-trolls-mobile-2.png\", \"lmc-trolls-mobile-3.png\", \"lmc-trolls-mobile-4.png\", \"lmc-trolls-desktop-1.png\", \"lmc-trolls-desktop-2.png\", \"lmc-trolls-desktop-3.png\"]','featured',9,'2021-07-27 14:54:12'),
	(11,X'11EC334E1DBF9C12B4DF25E613AA1F9A','La Mie Câline','[\"Website\"]','Battle 2 Choc',NULL,'Via une application en onglet de Page Facebook, inscris-toi, renseigne ton magasin La Mie Câline et dis-nous si tu considères qu’un pain au chocolat est une chocolatine (ou une chocolatine un pain au chocolat). Selon les votes, leur nom sera changé dans les magasins.',NULL,'[1, 2, 3, 4, 5, 6, 7]','lmc-battle_2_choc-thumbnail.png','[\"lmc-battle_2_choc-desktop-1.png\"]',NULL,NULL,'2021-07-27 14:55:58'),
	(12,X'11EC334E1DBF9F14B4DF25E613AA1F9A','La Mie Câline','[\"Website\"]','Allô c’est cado',NULL,'Via une application en onglet de Page Facebook, inscris-toi en donnant ton numéro de téléphone, tu seras peut-être appelé en direct lors du Facebook Live pour gagner des cadeaux !',NULL,'[1, 2, 3, 4, 5, 6, 7]','lmc-allo_cadeau-thumbnail.png','[\"lmc-allo_cadeau-desktop-1.png\", \"lmc-allo_cadeau-desktop-2.png\"]',NULL,NULL,'2021-07-27 14:57:07'),
	(13,X'11EC334E1DBFA054B4DF25E613AA1F9A','Leroy Merlin','[\"Website\"]','SocialWall','<p>L\'objectif de ce SocialWall, exposé dans différentes parties du magasin Leroy Merlin d\'Annecy, était de faire découvrir les comptes Facebook et Instagram aux visiteurs. Il utilisait le module Sixpans Liveboard (solution propriétaire) pour récupérer les flux, et l\'API wheather.com pour afficher la météo à 3 jours.</p>','Sur un écran sont regroupés le feed Facebook et Instagram du compte, l\'heure et la météo.',NULL,'[1, 2, 3, 4, 5, 6, 8]','leroymerlin-socialwall-thumbnail.png','[\"leroymerlin-socialwall-1.png\"]','featured',6,'2021-07-27 14:57:48'),
	(14,X'11EC334E1DBFA180B4DF25E613AA1F9A','LaRedoute','[\"Réalité Augmentée\"]','Tel Père, Tel Fils/Fille',NULL,'Filtre de Réalité Augmentée pour Facebook. Applique une paire de lunettes, une moustage et un noeud papillon aux 2 personnes reconnues par le filtre. La première personne contrôle le type d\'objets affichés selon son expression faciale.',NULL,'[3]','laredoute-tptf-thumbnail.png','[\"laredoute-tptf-1.png\"]',NULL,NULL,'2021-07-27 14:58:39'),
	(15,X'11EC334E1DBFA2A2B4DF25E613AA1F9A','LaRedoute','[\"Facebook Live\"]','Le but du jeu',NULL,'Facebook Live dans le cadre du PressDay LaRedoute pour présenter la nouvelle collection de maillots de bain. La présentation des maillots s\'enchaîne et les spectateurs sont incités à voter pour leur maillot préféré en commentaire du Live.',NULL,'[1, 2, 3]','laredoute-lebutdujeu-thumbnail.png','[\"laredoute-lebutdujeu-1.png\", \"laredoute-lebutdujeu-2.png\", \"laredoute-lebutdujeu-3.png\", \"laredoute-lebutdujeu-4.png\", \"laredoute-lebutdujeu-5.png\", \"laredoute-lebutdujeu-6.png\", \"laredoute-lebutdujeu-7.png\"]',NULL,NULL,'2021-07-27 15:02:50'),
	(16,X'11EC334E1DBFA478B4DF25E613AA1F9A','Intersport','[\"Facebook Live\", \"Objet connecté\"]','Noël 2017','<p>Outre le Facebook Live en lui-même (mise en place du matériel de captation et configuration du stream) un serveur récupérait en temps réel les commentaires et les Réactions du Live. Cela permettait de visualiser la popularité des #hashtags dans un BackOffice et d\'ouvrir les boîtes en fonction.</p>\n<p>Les Réactions, elles, déclenchaient l\'allumage d\'ampoules spécifiques à la Réaction utilisée (Like, Love, Haha) quand elles arrivaient sur le serveur, ainsi que l\'affichage de l\'image du profil au-dessus de ladite ampoule. Concrètement, quand un utilisateur likait la vidéo, il allumait l\'ampoule correspondante dans \"la vraie vie\" et voyait son image de profile s\'afficher au-dessus d\'elle, en incrustation vidéo.</p>','Deux boîtes remplies de lots à gagner dévoilent leur contenu au fur et à mesure des votes des spectateurs en commentaire du Live. Les lots de la première boîte complètement dévoilée sont répartis parmi les votants de cette boîte.',NULL,'[1, 2]','intersport-noel-thumbnail.png','[\"intersport-noel-1.png\", \"intersport-noel-2.png\", \"intersport-noel-3.png\", \"intersport-noel-4.png\", \"intersport-noel-5.png\"]','featured',7,'2021-07-27 15:05:20'),
	(17,X'11EC334E1DBFA5A4B4DF25E613AA1F9A','Intersport','[\"Website\"]','Vous allez adorer la rentrée',NULL,'Double opération pour la rentrée avec Intersport : un “calendrier de l’avent” des vacances d’été pour attendre la rentrée scolaire et un quiz de personnalité pour déterminer quel sport convient le mieux à l’enfant.',NULL,'[1, 2, 3, 4, 5, 6, 7]','intersport-calendrier_rentree-thumbnail.png','[\"intersport-calendrier_rentree-desktop-1.png\", \"intersport-calendrier_rentree-desktop-2.png\"]',NULL,NULL,'2021-07-27 15:07:05'),
	(18,X'11EC334E1DBFA6EEB4DF25E613AA1F9A','Intersport','[\"Messenger Bot\"]','Bot Messenger SAV','<p>Le Bot est créé avec la solution <a href=\"https://chatfuel.com/\" target=\"_blank\" rel=\"noopener\">Chatfuel</a> sur la Page Facebook Intersport. Il permet de répondre aux questions les plus courantes via un arbre décisionnel géré par des boutons (pas d’IA), mais aussi de trouver le magasin le plus proche de soi avec la géolocalisation et l\'API Google Places.</p>\n<p>Les informations principales des magasins sont alors directement récupérées de Google Places, avec les photos, les heures d\'ouvertures et même le temps de trajet avec les conditions de circulation actuelles.</p>','Bot Messenger de type SAV',NULL,'[1, 2]','intersport-bot_messenger-thumbnail.png','[\"intersport-bot_messenger-1.png\"]','featured',3,'2021-07-27 15:08:57'),
	(19,X'11EC334E1DBFC156B4DF25E613AA1F9A','Orange','[\"Website\", \"Twitter bot\"]','RugbyBattle',NULL,'Tweet avec #RugbyBattle + @AvecLeXV + #Allez[TonClub] pour soutenir ton club préféré. La réponse contient le pourcentage des votes actuel, repris sur un mini-site dédié.',NULL,'[1, 2, 3, 4, 5, 6, 8]','havas-rugby_battle-thumbnail.png','[\"havas-rugby_battle-ar-1.png\", \"havas-rugby_battle-ar-2.png\", \"havas-rugby_battle-ar-3.png\", \"havas-rugby_battle-desktop-1.png\", \"havas-rugby_battle-desktop-2.png\"]',NULL,NULL,'2021-07-27 15:10:04'),
	(20,X'11EC334E1DBFC340B4DF25E613AA1F9A','Orange','[\"Twitter Bot\"]','MyPerfectDraw',NULL,'Tweet avec #MyPerfectDraw et les #Equipes qui vont être dans le même groupe que la France à l\'Euro 2016. Si tu as fait le bon pronostic, tu peux gagner des cadeaux !',NULL,'[1, 2]','havas-final_draw-thumbnail.png','[\"havas-final_draw-1.png\"]',NULL,NULL,'2021-07-27 15:11:46'),
	(21,X'11EC334E1DBFC48AB4DF25E613AA1F9A','Altran','[\"Twitter Bot\"]','TweetAndFly',NULL,'Tweet #TweetAndFly + @altran pour commencer un quiz sur le projet SolarImpulse (avion à énergie solaire)',NULL,'[1, 2]','havas-solar_impulse-thumbnail.png','[\"havas-solar_impulse-1.png\", \"havas-solar_impulse-2.png\"]',NULL,NULL,'2021-07-27 15:19:44'),
	(22,X'11EC334E1DBFC5C0B4DF25E613AA1F9A','GEMO','[\"Twitter Bot\"]','StarWars',NULL,'Tweet #coteObscure ou #coteLumuneux + @Gemo_Officiel pour donner encourager l\'empire ou la résistance',NULL,'[1, 2]','gemo-star_wars-thumbnail.png','[\"gemo-star_wars-1.png\"]',NULL,NULL,'2021-07-27 15:20:48'),
	(23,X'11EC334E1DBFC750B4DF25E613AA1F9A','Firestone','[\"Website\", \"Concours\"]','Firestone Music Talents',NULL,'Via un minisite dédié, accessible au travers d’un sous domaine firestone.fr, le site FMT permettait aux internautes de voter pour leurs artistes préférés afin qu’ils soient qualifiés pour la finale du Firestone Music Talents. Le vainqueur pouvait se produire sur la scène Firestone au festival Rock en Seine, et un tirage au sort offrait des places aux internautes votants.',NULL,'[1, 2, 3, 4, 5, 6, 8]','firetone-fmt-thumbnail.png','[\"firetone-fmt-mobile-1.png\", \"firetone-fmt-mobile-2.png\", \"firetone-fmt-mobile-3.png\", \"firetone-fmt-desktop-1.png\", \"firetone-fmt-desktop-2.png\", \"firetone-fmt-desktop-3.png\"]',NULL,NULL,'2021-07-27 16:37:11'),
	(24,X'11EC334E1DBFC8AEB4DF25E613AA1F9A','Perso','[\"Réalité Augmentée\"]','Eligos',NULL,'Filtre Instagram de réalité augmenté. Reproduit l\'effet de glitch utilisé par la série \"Ash vs. Evil Dead\" pour l\'intervention du démon Eligos.',NULL,'[3]','eligos-thumbnail.png','[\"eligos.png\"]',NULL,NULL,'2021-07-27 16:39:27'),
	(25,X'11EC334E1DBFC9D0B4DF25E613AA1F9A','EDF Luminus','[\"Website\"]','Mes résolutions durables',NULL,'Via un minisite dédié, les internautes pouvaient générer leur “résolution durable” pour 2019. L’idée : aider par de petits gestes à être plus responsables vis-à-vis de la planète. A la fin de l’expérience, chaque partage compte : 1 partage = 1 arbre planté.',NULL,'[1, 2, 3, 4, 5, 6, 7]','edf-luminus_resolutions_durables-thumbail.png','[\"edf-luminus_resolutions_durables-desktop-1.png\", \"edf-luminus_resolutions_durables-desktop-2.png\", \"edf-luminus_resolutions_durables-desktop-3.png\", \"edf-luminus_resolutions_durables-desktop-4.png\"]',NULL,NULL,'2021-07-27 16:41:14'),
	(26,X'11EC334E1DBFCB9CB4DF25E613AA1F9A','Devred','[\"Website\"]','SocialWall',NULL,'SocialWall reprenant le feed Instagram de Devred, ainsi que le nombre d’abonnés FB, IG et TW.',NULL,'[1, 2, 3, 4, 5, 6, 8]','devred-socialwall-thumbnail.png','[\"devred-socialwall-1.png\"]',NULL,NULL,'2021-07-27 16:41:44'),
	(27,X'11EC334E1DBFCCB4B4DF25E613AA1F9A','Devred','[\"Website\"]','Opération privilège',NULL,'Application Facebook de recrutement de fans, hébergée en iFrame sur le site Devred. Les internautes sont invités à devenir fans de la Page Facebook pour profiter des privilèges. Un tirage au sort était fait sur les personnes converties d’une part et non-converties d’autre part.',NULL,'[1, 2, 3, 4, 5, 6, 7]','devred-operation_privilege-thumbnail.png','[\"devred-operation_privilege-desktop-1.png\"]',NULL,NULL,'2021-07-27 16:43:52'),
	(28,X'11EC334E1DBFCE9EB4DF25E613AA1F9A','Cyrillus','[\"Website\"]','Le Jeu des Tribus',NULL,'Via un minisite dédié, joue à plusieurs activités : un quiz de personnalité de la famille, un concours photo et un concours de “mots d’enfants”.',NULL,'[1, 2, 3, 4, 5, 6, 7]','cyrillus-jeu_des_tribus-thumbnail.png','[\"cyrillus-jeu_des_tribus-desktop-1.png\", \"cyrillus-jeu_des_tribus-desktop-2.png\", \"cyrillus-jeu_des_tribus-desktop-3.png\", \"cyrillus-jeu_des_tribus-desktop-4.png\", \"cyrillus-jeu_des_tribus-desktop-5.png\", \"cyrillus-jeu_des_tribus-desktop-6.png\", \"cyrillus-jeu_des_tribus-mobile-1.png\"]',NULL,NULL,'2021-07-27 16:45:07'),
	(29,X'11EC334E1DBFD060B4DF25E613AA1F9A','Clarins','[\"Réalité Augmentée\"]','L’arbre à coeurs','<p>C\'est en partenariat avec une illustratrice que ce filtre a vu le jour, pour le compte de Clarins. Il a fallu reprendre l\'illustration originale pour l\'animer, tout en restant dans la limite de poids imposée par Instagram (4Mo).</p>\n<p>L\'animation de la liane et des coeurs a été géré entièrement par le code pour satisfaire ces exigeances.</p>','Filtre de réalité augmentée sur Instagram qui fait progresser une liane avec des coeurs qui battent autour du visage de l’utilisateur.',NULL,'[3]','clarins-arbre_a_coeurs-thumbnail.png','[\"clarins-arbre_a_coeurs-1.png\"]','featured',8,'2021-07-27 16:49:40'),
	(30,X'11EC334E1DBFD18CB4DF25E613AA1F9A','Cémoi','[\"Website\"]','Le jardin des Mojis',NULL,'Via un minisite dédié, les internautes pouvaient revenir chaque jour pour découvrir un nouveau contenu disponible : une vidéo, une image, un jeu, … pour gagner des cadeaux tout au long de la période de jeu. Les images et vidéos étaient le relai de l’animation de la Page Facebook.',NULL,'[1, 2, 3, 4, 5, 6, 7]','cemoi-jardin_des_moji-thumbnail.png','[\"cemoi-jardin_des_moji-mobile-1.png\", \"cemoi-jardin_des_moji-mobile-2.png\", \"cemoi-jardin_des_moji-mobile-3.png\", \"cemoi-jardin_des_moji-mobile-4.png\", \"cemoi-jardin_des_moji-mobile-5.png\", \"cemoi-jardin_des_moji-desktop-1.png\", \"cemoi-jardin_des_moji-desktop-2.png\", \"cemoi-jardin_des_moji-desktop-3.png\", \"cemoi-jardin_des_moji-desktop-4.png\", \"cemoi-jardin_des_moji-desktop-5.png\"]',NULL,NULL,'2021-07-27 16:50:50'),
	(31,X'11EC334E1DBFD34EB4DF25E613AA1F9A','Crédit Agricole','[\"Website\"]','La Compo Bleue',NULL,'Via l’agence HAVAS sur une application intégrée en iframe sur le site du Crédit Agricole, on récupère la popularité des joueurs de foot français sur internet via Digimind (outil d’agrégation de données sociales). On affiche ainsi en quasi temps réel la composition de l’équipe de France de foot pour l’Euro (11 titulaires + suppléants) selon les goûts des français.',NULL,'[1, 2, 3, 4, 5, 6, 8]','ca-la_compo_bleue-thumbnail.png','[\"ca-la_compo_bleue-1.png\"]',NULL,NULL,'2021-07-27 16:53:20'),
	(32,X'11EC334E1DBFD470B4DF25E613AA1F9A','Bridgestone','[\"Facebook Live\"]','Interview Charlotte Bonnet',NULL,'Facebook Live de questions/réponses avec Charlotte Bonnet, championne de natation et égérie Bridgsetone. Les questions sont modérées en temps réel et affichées directement sur le Live.',NULL,'[1, 2, 3]','bridgestone-live_charlotte_bonnet-thumbnail.png','[\"bridgestone-live_charlotte_bonnet-1.png\", \"bridgestone-live_charlotte_bonnet-2.png\", \"bridgestone-live_charlotte_bonnet-3.png\", \"bridgestone-live_charlotte_bonnet-4.png\", \"bridgestone-live_charlotte_bonnet-5.png\"]',NULL,NULL,'2021-07-27 16:55:24'),
	(33,X'11EC334E1DBFD628B4DF25E613AA1F9A','Betclic','[\"Twitter Bot\"]','TFC 80ans',NULL,'Tweet #Dici80ansLeTFC + @betclic et complète la phrase qui t\'es proposée (en étant drôle si possible)',NULL,'[1, 2]','betclic-tfc80ans-thumbnail.png','[\"betclic-tfc80ans-1.png\", \"betclic-tfc80ans-2.png\", \"betclic-tfc80ans-3.png\", \"betclic-tfc80ans-4.png\", \"betclic-tfc80ans-5.png\", \"betclic-tfc80ans-6.png\"]',NULL,NULL,'2021-07-27 16:56:56'),
	(34,X'11EC334E1DBFD772B4DF25E613AA1F9A','Betclic','[\"Website\"]','TuPréfères','<p>Le principal challenge de cette opération était d\'absobrer le traffic et le flux de participations. À chaque push notification de Betclic, c\'est presque <strong>1500 requêtes par secondes</strong> qui ont été traitées, pour plus de <strong>9 milions de participations</strong> au total.</p>\n<p>L\'architecture Heroku avec son scaling horizontal et vertical a été grandement mis à contribution. Des optimisations de requêtes SQL et des techniques de mise en cache sur-mesure côté serveur ont également été nécessaires pour que l\'opération soit un succès.</p>','Via un mini-site en 3 langues  (français, portugais et polonais), choisis ce que tu préfères parmi 2 situations. Selon ta réponse, des badges sont à débloquer et ta progression sauvegardée si tu crées un compte.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-tu_preferes-thumbnail.png','[\"betclic-tu_preferes-mobile-1.png\", \"betclic-tu_preferes-mobile-2.png\", \"betclic-tu_preferes-mobile-3.png\", \"betclic-tu_preferes-mobile-4.png\", \"betclic-tu_preferes-mobile-5.png\", \"betclic-tu_preferes-mobile-6.png\", \"betclic-tu_preferes-desktop-1.png\", \"betclic-tu_preferes-desktop-2.png\", \"betclic-tu_preferes-desktop-3.png\"]','featured',1,'2021-07-27 17:00:03'),
	(35,X'11EC334E1DC00710B4DF25E613AA1F9A','Betclic','[\"Website\", \"Twitter Bot\"]','PlayWithTony',NULL,'Via une application d’onglet de Page Facebook, inscris-toi et tente ta chance à l’IG > des images de phases de jeu de basket s\'enchaînent (l’utilisateur a le choix entre faire une passe, passer en force, etc...), si à la fin le panier est marqué c’est gagné. Sur Twitter, Tweet #PlayWithTony + @Betclic + @ami1 (1 ou 2 mentions possibles) et commence le match pour gagner des cadeaux.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-play_with_tony-thumbnail.png','[\"betclic-play_with_tony-desktop-1.png\", \"betclic-play_with_tony-desktop-2.png\", \"betclic-play_with_tony-desktop-3.png\", \"betclic-play_with_tony-mobile-1.png\", \"betclic-play_with_tony-ar-1.png\", \"betclic-play_with_tony-ar-2.png\", \"betclic-play_with_tony-ar-3.png\"]',NULL,NULL,'2021-07-27 17:01:58'),
	(36,X'11EC334E1DC0097CB4DF25E613AA1F9A','Betclic','[\"Website\"]','La Meilleure Excuse',NULL,'Via un mini-site, génère une excuse qui te permettra de regarder ton match de foot tranquillement. 3 niveaux d’excuses sont disponibles, de la plus probable à la plus improbable.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-meilleure_excuse-thumbnail.png','[\"betclic-meilleure_excuse-mobile-1.png\", \"betclic-meilleure_excuse-mobile-2.png\", \"betclic-meilleure_excuse-mobile-3.png\", \"betclic-meilleure_excuse-desktop-1.png\", \"betclic-meilleure_excuse-desktop-2.png\", \"betclic-meilleure_excuse-desktop-3.png\", \"betclic-meilleure_excuse-desktop-4.png\"]',NULL,NULL,'2021-07-27 17:03:57'),
	(37,X'11EC334E1DC00AF8B4DF25E613AA1F9A','Betclic','[\"Website\"]','LOL Bet Center',NULL,'Via un mini-site, génère un pronostic ou un bingo que tu postes sur Twitter avec @betclic. Si le pronostic s\'avère juste, ou si tu remplis ta grille de bingo durant le match, c\'est gagné !',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-lol_bet_center-thumbnail.png','[\"betclic-lol_bet_center-mobile-1.png\", \"betclic-lol_bet_center-mobile-2.png\", \"betclic-lol_bet_center-mobile-3.png\", \"betclic-lol_bet_center-mobile-4.png\", \"betclic-lol_bet_center-desktop-1.png\", \"betclic-lol_bet_center-desktop-2.png\", \"betclic-lol_bet_center-desktop-3.png\", \"betclic-lol_bet_center-desktop-4.png\"]',NULL,NULL,'2021-07-27 17:05:42'),
	(38,X'11EC334E1DC00C56B4DF25E613AA1F9A','Betclic','[\"Website\"]','Mon Futur Club',NULL,'Via un mini-site, découvre dans quel club tu vas être transféré, mais surtout le montant du transfert !',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-futur_club-thumbnail.png','[\"betclic-futur_club-mobile-1.png\", \"betclic-futur_club-mobile-2.png\", \"betclic-futur_club-mobile-3.png\", \"betclic-futur_club-desktop-1.png\", \"betclic-futur_club-desktop-2.png\", \"betclic-futur_club-desktop-3.png\"]',NULL,NULL,'2021-07-27 17:08:05'),
	(39,X'11EC334E1DC00D82B4DF25E613AA1F9A','Betclic','[\"Facebook Live\"]','Decibel Battle',NULL,'Commente #TON_EQUIPE pour l\'encourager et faire monter la jauge ! Les gagnants seront tirés au sort parmi les supporters de l\'équipe gagnante !',NULL,'[1, 2]','betclic-decibels_battle-thumbnail.png','[\"betclic-decibels_battle-1.png\"]',NULL,NULL,'2021-07-27 17:10:33'),
	(40,X'11EC334E1DC00EAEB4DF25E613AA1F9A','Betclic','[\"Website\"]','Ma Carte Parieur',NULL,'Via un mini-site dédié, crée ton avatar et renseigne ton pseudo Betclic. Un appel à la base de données Betclic te génère ta “carte parieur” en fonction de tes statistiques (paris gagné ou perdus, meilleure côte gagnée, etc...).',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-carte_parieur-thumbnail.png','[\"betclic-carte_parieur-desktop-1.png\"]',NULL,NULL,'2021-07-27 17:14:22'),
	(41,X'11EC334E1DC00FF8B4DF25E613AA1F9A','Betclic','[\"Website\"]','Ton Match',NULL,'Via un minisite dédié, les internautes pouvaient entrer leur prénom et celui de l’être aimé. L’application générait un “match”, composé des 2 prénoms, d’une côte et d’une description humoristique. Le match était téléchargeable en image et partageable sur les réseaux sociaux.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-ton_match-thumbnail.png','[\"betclic-ton_match-mobile-1.png\", \"betclic-ton_match-mobile-2.png\", \"betclic-ton_match-mobile-3.png\", \"betclic-ton_match-mobile-4.png\", \"betclic-ton_match-desktop-1.png\", \"betclic-ton_match-desktop-2.png\", \"betclic-ton_match-desktop-3.png\", \"betclic-ton_match-desktop-4.png\", \"betclic-ton_match-desktop-5.png\"]',NULL,NULL,'2021-07-27 17:16:22'),
	(42,X'11EC334E1DC09680B4DF25E613AA1F9A','Betclic','[\"Messenger Bot\", \"Twitter bot\", \"Instagram bot\"]','Bot SAV','<p>Le Bot est créé avec la solution <a href=\"https://chatfuel.com/\" target=\"_blank\" rel=\"noopener\">Chatfuel</a> pour ses versions Messenger et Instagram, et in-house pour la version Twitter. Il permet aux utilisateurs de trouver en autonomie totale les réponses aux questions les plus courantes (et d\'alléger la charge des CM).</p>\n<p>Même dans sa version Chatfuel, le Bot dialogue avec le serveur pour fournir des statistiques plus poussées et dégager des KPIs pertinents. Il répond aux questions les plus fréquentes avec un arbre décisionnel et des boutons (pas d’IA).</p>','Bot type SAV décliné en 3 langues (français, portugais et polonais) sur 3 canaux (Messenger, Instagram et Twitter).',NULL,'[1, 2]','betclic-bot_sav-thumbnail.png','[\"betclic-bot_sav-twitter-1.png\", \"betclic-bot_sav-twitter-2.png\", \"betclic-bot_sav-twitter-3.png\", \"betclic-bot_sav-twitter-4.png\", \"betclic-bot_sav-twitter-5.png\", \"betclic-bot_sav-twitter-6.png\", \"betclic-bot_sav-messenger-1.png\", \"betclic-bot_sav-messenger-2.png\", \"betclic-bot_sav-messenger-3.png\", \"betclic-bot_sav-messenger-4.png\", \"betclic-bot_sav-messenger-5.png\", \"betclic-bot_sav-messenger-6.png\"]','featured',10,'2021-07-27 17:19:20'),
	(43,X'11EC334E1DC09892B4DF25E613AA1F9A','Betclic','[\"Website\"]','Betclic Awards',NULL,'Via un mini-site, fais ton pronostic sur les joueurs et joueuses qui ont été les plus pariés en 2019.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-awards-thumbnail.png','[\"betclic-awards-mobile-1.png\", \"betclic-awards-mobile-2.png\", \"betclic-awards-mobile-3.png\", \"betclic-awards-mobile-4.png\", \"betclic-awards-desktop-1.png\", \"betclic-awards-desktop-2.png\", \"betclic-awards-desktop-3.png\", \"betclic-awards-desktop-4.png\", \"betclic-awards-desktop-5.png\"]',NULL,NULL,'2021-07-27 17:22:05'),
	(44,X'11EC334E1DC099F0B4DF25E613AA1F9A','Betclic','[\"Website\"]','Au Stade Avec Betclic',NULL,'Via un mini-site, inscris-toi pour gagner des places pour tes matches préférés !',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-au_stade-thumbnail.png','[\"betclic-au_stade-mobile-1.png\", \"betclic-au_stade-mobile-2.png\", \"betclic-au_stade-mobile-3.png\", \"betclic-au_stade-desktop-1.png\", \"betclic-au_stade-desktop-2.png\", \"betclic-au_stade-desktop-3.png\"]',NULL,NULL,'2021-07-27 17:24:44'),
	(45,X'11EC334E1DC09B1CB4DF25E613AA1F9A','Beiersdorf','[\"Website\"]','SocialWall',NULL,'SocialWall interactif affichant les feed FB et IG des univers Beiersdorf (NIVEA, NIVEA MEN, EUCERIN, FLORENA), ainsi que le flux du #NaturallyGood, des avis clients sur les produits NaturallyGood et le bot conversationnel NaturallyGood.',NULL,'[1, 2, 3, 4, 5, 6, 8]','beiersdorf-socialwall-thumbnail.png','[\"beiersdorf-socialwall-1.png\", \"beiersdorf-socialwall-2.png\", \"beiersdorf-socialwall-3.png\", \"beiersdorf-socialwall-4.png\", \"beiersdorf-socialwall-5.png\"]',NULL,NULL,'2021-07-27 17:26:45'),
	(46,X'11EC334E1DC09C7AB4DF25E613AA1F9A','Banane de Guadeloupe et Martinique','[\"Website\", \"Gameplay\"]','La Bananeraie',NULL,'Via l’agence Hopscotch avec une application d’onglet de Page Facebook, inscris-toi et trouve le plus vite possible les éléments qui se sont cachés aléatoirement dans cette bananeraie (oiseau, caméléon, ...). Hisse-toi au top du classement des meilleurs scores.',NULL,'[1, 2, 3, 4, 5, 6, 7]','banane-martinique-bananeraie-thumbnail.png','[\"banane-martinique-bananeraie-1.png\"]',NULL,NULL,'2021-07-27 17:28:35'),
	(47,X'11EC334E1DC09DA6B4DF25E613AA1F9A','ArianeGroup','[\"Twitter Bot\"]','Quiz Bepicolombo',NULL,'Envoyez #startQuizAriane en DM au compte @Arianegroup et commencez un quiz sur la mission Bepicolombo.',NULL,'[1, 2]','ariane-quiz_bepicolombo-thumbnail.png','[\"ariane-quiz_bepicolombo-1.png\", \"ariane-quiz_bepicolombo-2.png\"]',NULL,NULL,'2021-07-27 17:31:00'),
	(48,X'11EC334E1DC09EDCB4DF25E613AA1F9A','ArianeGroup','[\"Facebook Live\"]','Lancements Ariane',NULL,'Reprise en Facebook Live des lancements de fusées Ariane. Un compteur de Reactions du Live en temps réel est visible directement dans la vidéo. Pour le lancement VA247, des questions étaient directement posées dans la vidéo pour que les spectateurs y répondent.',NULL,'[1, 2]','arianegroup-launches-thumbnail.png','[\"arianegroup-launches-1.png\", \"arianegroup-launches-2.png\", \"arianegroup-launches-3.png\", \"arianegroup-launches-4.png\", \"arianegroup-launches-5.png\", \"arianegroup-launches-6.png\", \"arianegroup-launches-7.png\", \"arianegroup-launches-8.png\", \"arianegroup-launches-9.png\", \"arianegroup-launches-10.png\", \"arianegroup-launches-11.png\", \"arianegroup-launches-12.png\", \"arianegroup-launches-13.png\", \"arianegroup-launches-14.png\", \"arianegroup-launches-15.png\", \"arianegroup-launches-16.png\"]',NULL,NULL,'2021-07-27 17:32:13'),
	(49,X'11EC334E1DC0A0B2B4DF25E613AA1F9A','ArianeGroup','[\"Twitter Bot\"]','Ariane Club',NULL,'Tweet #ArianeClub + @arianeGroup et reçois ta carte de membre. Si tu as une carte en or, tu as gagné un cadeau !',NULL,'[1, 2]','arianegroup-ariane_club-thumbnail.png','[\"arianegroup-ariane_club-1.png\"]',NULL,NULL,'2021-07-27 17:34:49'),
	(50,X'11EC334E1DC0A2A6B4DF25E613AA1F9A','Betclic','[\"Website\"]','Quel Parieur Es-tu ?',NULL,'Quiz de personnalité calculant un profil de parieur, parmi 16 profils. La première question détermine la deuxième, la deuxième question détermine un quiz de 5 questions qui va calculer le profil final.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-types_parieurs-thumbnail.png','[\"betclic-types_parieurs-mobile-1.png\", \"betclic-types_parieurs-mobile-2.png\", \"betclic-types_parieurs-mobile-3.png\", \"betclic-types_parieurs-mobile-4.png\", \"betclic-types_parieurs-mobile-5.png\", \"betclic-types_parieurs-desktop-1.png\", \"betclic-types_parieurs-desktop-2.png\", \"betclic-types_parieurs-desktop-3.png\", \"betclic-types_parieurs-desktop-4.png\"]',NULL,NULL,'2021-07-27 17:36:31'),
	(51,X'11EC334E1DC0A53AB4DF25E613AA1F9A','Rians','[\"Website\"]','La Carte Blanche',NULL,'Landing Page pour les produits faisselle de Rians, relayée par la campagne Facebook Ads.',NULL,'[1, 2, 3, 4, 5, 6, 8]','rians-carte_blanche-thumbnail.pngrians-carte_blanche-thumbnail.png','[\"rians-carte_blanche-mobile-1.png\", \"rians-carte_blanche-desktop-1.png\"]',NULL,NULL,'2021-07-27 17:38:53'),
	(52,X'11EC334E1DC0A6A2B4DF25E613AA1F9A','Betclic','[\"Website\"]','Le Rewind',NULL,'Quiz pour les 15ans de Betclic. Chaque quiz de 10 questions (choisies aléatoirement parmi des pools de 100 questions) pose des questions sur Betclic et le sport en général sur une période donnée, de 2006 à 2021. Une note est attribuée à la fin selon le nombre de bonnes réponses.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-rewind-thumbnail.png','[\"betclic-rewind-mobile-1.png\", \"betclic-rewind-mobile-2.png\", \"betclic-rewind-mobile-3.png\", \"betclic-rewind-mobile-4.png\", \"betclic-rewind-mobile-5.png\", \"betclic-rewind-mobile-6.png\", \"betclic-rewind-desktop-1.png\", \"betclic-rewind-desktop-2.png\", \"betclic-rewind-desktop-3.png\", \"betclic-rewind-desktop-4.png\", \"betclic-rewind-desktop-5.png\"]',NULL,NULL,'2021-07-27 17:40:09'),
	(53,X'11EC334E1DC0A832B4DF25E613AA1F9A','Betclic','[\"Website\"]','QI Foot',NULL,'Quiz pour l’Euro de football, décliné en 3 langues (FR, PT, PL). 4 sessions de Quiz, avec 120s pour répondre à un maximum de questions. A la fin, un score est déterminé avec le nombre de bonnes réponses, et un classement établi avec des personnalités qui ont également répondu au quiz.',NULL,'[1, 2, 3, 4, 5, 6, 7]','betclic-qi_foot-thumbnail.png','[\"betclic-qi_foot-mobile-1.png\", \"betclic-qi_foot-mobile-2.png\", \"betclic-qi_foot-mobile-3.png\", \"betclic-qi_foot-mobile-4.png\", \"betclic-qi_foot-mobile-5.png\", \"betclic-qi_foot-mobile-6.png\", \"betclic-qi_foot-desktop-1.png\", \"betclic-qi_foot-desktop-2.png\", \"betclic-qi_foot-desktop-3.png\", \"betclic-qi_foot-desktop-4.png\", \"betclic-qi_foot-desktop-5.png\", \"betclic-qi_foot-desktop-6.png\", \"betclic-qi_foot-desktop-7.png\"]',NULL,NULL,'2021-07-27 17:42:09'),
	(54,X'11EC334E1DC0A9B8B4DF25E613AA1F9A','Norauto','[\"Website\"]','PitStopChallenge','La description','Mini-site relai de la mini-série de télé-réalité Norauto #PitStopChallenge diffusée sur Youtube. Les tweets du #PitStopChallenge sont relayés sur le site, ainsi que les vidéos Youtube au fur et à mesure de leur diffusion. La fiche de présentation des différents candidats est également disponible.',NULL,'[1, 2, 3, 4, 5, 6, 8]','norauto-pitstopchallenge-thumbnail.png','[\"norauto-pitstopchallenge-desktop-1.png\", \"norauto-pitstopchallenge-mobile-1.png\"]',NULL,NULL,'2021-07-27 17:44:37'),
	(55,X'11EC39A7BED4B51AB4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Login','<p>C\'est ce module qui va gérer les utilisateurs (création/identification) mais aussi le monitoring et les statistiques d\'utilisations.</p>\n<p>Mais ce qui fait la valeur ajoutée de Sixpans Login est l\'espace personnalisé disponible pour les clients, dans lequel ils peuvent retrouver :\n<ul>\n<li>leur équipe dédiée et son contact\n<li>les ressources qui leur sont partagées\n<li>la liste des devis et factures\n<li>une vue sur leurs investissements Ads\n<li>une veille personnalisée des réseaux sociaux\n</ul>\n</p>\n<p>\nUne section spéciale pour les responsables de comptes clients leur permet de voir le temps passé sur chaque poste (créa, avant-vente, ...) directement issu de l\'ERP, pour avoir une vue sur la rentabilité client.</p>','Sixpans Login est le hub central de la suite d\'applications.',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-login-thumbnail.png','[\"sixpans-login-desktop-1.png\", \"sixpans-login-desktop-2.png\", \"sixpans-login-desktop-3.png\", \"sixpans-login-desktop-4.png\", \"sixpans-login-desktop-5.png\"]','sixpans',1,'2021-10-29 17:42:05'),
	(56,X'11EC39A7BED61B1CB4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Reporting','<p>Le module Reporting aide les Community Managers et responsables de comptes à être plus productifs en automatisant et formattant les reporting KPIs.</p>\n<p>Les tâches les plus répétitives sont prises en charge, comme par exemple la génération instantanée de présentations Keynote ou PowerPoint incluant directement les KPIs dans les tableaux. Cela évite les copier/coller fastidieux et source d\'erreurs.</p>\n<p>Le module permet également de s\'abonner à des comptes sociaux pour recevoir des notifications en temps réel :\n<ul>\n<li>Rappel de bilan avec les chiffres clés</li>\n<li>Envoi des KPIs de Posts après un nombre de jours personnalisable</li>\n<li>Envoi des performances de campagnes Ads</li>\n</ul>','Reporting et monitoring des comptes Facebook, Instagram, Twitter, LinkedIn, Facebook Ads et LinkedIn Ads',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-reporting-thumbnail.png','[\"sixpans-reporting-desktop-1.png\", \"sixpans-reporting-desktop-2.png\", \"sixpans-reporting-desktop-3.png\", \"sixpans-reporting-desktop-4.png\", \"sixpans-reporting-desktop-5.png\", \"sixpans-reporting-desktop-6.png\", \"sixpans-reporting-desktop-7.png\", \"sixpans-reporting-desktop-8.png\", \"sixpans-reporting-desktop-9.png\", \"sixpans-reporting-desktop-10.png\", \"sixpans-reporting-desktop-11.png\", \"sixpans-reporting-desktop-12.png\", \"sixpans-reporting-desktop-13.png\", \"sixpans-reporting-desktop-14.png\", \"sixpans-reporting-desktop-15.png\", \"sixpans-reporting-desktop-16.png\", \"sixpans-reporting-desktop-17.png\", \"sixpans-reporting-desktop-18.png\", \"sixpans-reporting-desktop-19.png\"]','sixpans',2,'2021-10-29 17:42:05'),
	(57,X'11EC39A7BED64EE8B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','PowerUp Trello','<p>Ce <a href=\"https://blog.trello.com/fr/trello-power-ups-gratuits\" target=\"_blank\" title=\"PowerUp Trello\" rel=\"noopener\">PowerUp Trello</a> a différentes fonctionnalités qui répondent à différentes problématiques.</p>\n<p><strong>Aide à la décision</strong><br>\nIl permet de prévisualiser au sein des cartes Trello les images et vidéos dans des posts Facebook, Instagram et LinkedIn, des carrousels de photos ou un feed entier Instagram. Le gain de temps est considérable car il affranchit le graphiste d\'un mockup et permet au client de se projeter directement dans la publication sur ses réseaux sociaux.\n</p>\n<p>Une autre fonctionnalité est de pouvoir gérer ses investissments Ads directement au sein des cartes Trello, et de définir des budgets mensuels. On voit alors sans quitter l\'interface :\n<ul>\n<li>Quel est le budget Ads mensuel</li>\n<li>Combien de campagnes sont sponsorisées</li>\n<li>Le budget restant et surtout son éventuel dépassement</li>\n</ul>\n</p>\n<p>\n<strong>Optimisation de la productivité</strong><br>\nLe PowerUp permet aussi de télécharger toutes les pièces jointes d\'une card en un clic dans une archive .zip, ce qui est beaucoup plus efficace que de télécharger toutes les pièces jointes une à une.\n</p>\n<p>La dernière fonctionnalité est de pouvoir intégrer (embed) des médias Facebook, Instagram, TikTok, Youtube et LinkedIn. On peut donc visualiser directement une inspiration (ou la réalisation finale d\'un projet) directement dans Trello.\n</p>\n','PowerUp Trello pour l\'aide à la décision et optimisation de la productivité.',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-trello-thumbnail.png','[\"sixpans-trello-desktop-1.png\", \"sixpans-trello-desktop-2.png\", \"sixpans-trello-desktop-3.png\", \"sixpans-trello-desktop-4.png\", \"sixpans-trello-desktop-5.png\", \"sixpans-trello-desktop-6.png\"]','sixpans',3,'2021-10-29 17:42:05'),
	(58,X'11EC39A7BED67864B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Billing','<p>Ce module est essentiellement à destination de l\'interne. Il aide notamment à optimiser l\'utilisation de l\'ERP en intégrant via son API des fonctionnalités qui ne sont pas disponibles dans l\'interface native :\n<ul>\n<li>Mesurer les performances des différentes BUs en analysant les ventes réalisées au niveau des prestations</li>\n<li>Effectuer des contrôles de saisie des temps pour mesurer la rentabilité des clients</li>\n</ul>\n</p>\n<p>Le module permet également de faire un suivi et un contrôle des investissments Ads en s\'interfaçant d\'un côté chez Facebook pour voir ce qui est dépensé, et de l\'autre côté dans l\'ERP pour voir ce qui est vendu. L\'équipe de Trafic Manager a donc la vue en temps réel de l\'investissement total, disponible ou engagé. C\'est un module essentiel pour pouvoir piloter parfois plusieurs centaines de milliers d\'euros d\'investissement média.</p>','Aide à la gestion d\'entreprise et contrôle des investissements Ads',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-billing-thumbnail.png','[\"sixpans-billing-desktop-1.png\", \"sixpans-billing-desktop-2.png\", \"sixpans-billing-desktop-3.png\", \"sixpans-billing-desktop-4.png\", \"sixpans-billing-desktop-5.png\", \"sixpans-billing-desktop-6.png\"]','sixpans',4,'2021-10-29 17:42:05'),
	(59,X'11EC39A7BED67A62B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Concours Facebook','<p>Il est fréquent de voir sur les réseaux des concours du type <i>\"Postez un commentaire et gagnez un cadeau en tirage au sort !\"</i>. Mais concrètement, comment le mettre en place en toute impartialité quand il y a plusieurs milliers de commentaires ? Et comment prévenir les 200 gagnants dudit concours ?</p>\n<p>C\'est typiquement ce genre de besoin auquel le module répond en :\n<ul>\n<li>permettant d\'extraire tous les commentaires ou likes d\'un Post en particulier</li>\n<li>de créer les règles du tirage au sort (mot ou expression dans le commentaire, nombre maximal/minimal de likes, dates de participations, etc...)</li>\n<li>de programmer l\'extraction (pour ne pas devoir la faire à la main à minuit)</li>\n<li>de déterminer automatiquement un nombre de gagnants</li>\n<li>de répndre en 1 clic à tous les commentaires gagnants</li>\nUn historique des concours réalisés est disponible, avec la possibilitéde les relancer ou de re-télécharger le résultat.\n</p>','Gestion de Concours sur Facebook et Instagram, via les commentaires d\'un post ou ses likes.',NULL,'[1, 2, 3, 4, 5, 6, 7]','sixpans-facebook-tas-thumbnail.png','[\"sixpans-facebook-tas-desktop-1.png\", \"sixpans-facebook-tas-desktop-2.png\", \"sixpans-facebook-tas-desktop-3.png\", \"sixpans-facebook-tas-desktop-4.png\", \"sixpans-facebook-tas-desktop-5.png\", \"sixpans-facebook-tas-desktop-6.png\", \"sixpans-facebook-tas-desktop-7.png\", \"sixpans-facebook-tas-desktop-8.png\", \"sixpans-facebook-tas-desktop-9.png\"]','sixpans',7,'2021-10-29 17:42:05'),
	(60,X'11EC39A7BED67BC0B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Concours Twitter','<p>La création de concours via ce module permet de télécharger en format .xlsx tous les tweets contenant une liste de #hashtags ou @mentions particulière. Cela permet de faire de la veille, de mesurer la popularité d\'un #hashtag mais également de tirer au sort automatiquement un nombre de gagnants :\n<ul>\n<li>en filtrant des mots ou expressions dans le tweet</li>\n<li>avec une extraction programmée (pour ne pas devoir la faire à la main à minuit)</li>\n</p>','Gestion de Concours sur Twitter avec la mise en place d\'écoute du stream sur une combinaison de #hashtags et @mentions.',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-twitter-tas-thumbnail.png','[\"sixpans-twitter-tas-desktop-1.png\", \"sixpans-twitter-tas-desktop-2.png\", \"sixpans-twitter-tas-desktop-3.png\", \"sixpans-twitter-tas-desktop-4.png\"]','sixpans',8,'2021-10-29 17:42:05'),
	(61,X'11EC39A7BED67CF6B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Hosting','<p>L\'histoire de ce module commence avec cette simple question : <i>Quelle est l\'URL du règlement pour mon jeu-concours sur Facebook ?</i></p>\n<p>La réponse s\'est matérialisée sous la forme d\'un module d\'hébergement de fichiers, avec :\n<ul>\n<li>la possibilité de les mettre à jour sans changer leur URL</li>\n<li>créer des liens courts avec un BitLy Connect</li>\n<li>leur associer une description pour se souvenir de leur rôle</li>\n</ul>\nLe gain de productivité pour les utilisateurs s\'est révélé accru puisque le jeu-concours se gère également par Sixpans.</p>\n<p>L\'arrivée du RGPD a donné encore plus de sens à ce module car il a évolué pour répondre à cette autre question : <i>Comment puis-je transmettre de manière sécurisée les gagnants du concours à mon client ?</i>\n<p>J\'ai alors ajouté la possibilité de :\n<ul>\n<li>protéger les fichiers avec un mot de passe</li>\n<li>imposer une durée de vie à un partage de fichier</li>\n<li>supprimer physiquement un fichier au bout d\'un certain temps</li>\n</ul>\nD\'autres fonctionnalités pour la productivité se sont aussi ajoutées au fil du temps, comme la génération de vignettes d\'aperçu pour les vidéos lorsqu\'elles sont ajoutées en pièce jointe d\'une carte Trello.\n</p>','Hébergement et sécurisation de fichiers en ligne',NULL,'[1, 2, 3, 4, 5, 6, 7]','sixpans-hosting-thumbnail.png','[\"sixpans-hosting-desktop-1.png\", \"sixpans-hosting-desktop-2.png\", \"sixpans-hosting-desktop-3.png\", \"sixpans-hosting-desktop-4.png\", \"sixpans-hosting-desktop-5.png\", \"sixpans-hosting-desktop-6.png\"]','sixpans',6,'2021-10-29 17:42:05'),
	(62,X'11EC39A7BED67E18B4DF25E613AA1F9A','Sixpans','[\"Productivité\"]','Liveboard','<p>Le Liveboard, un des modules phares de Sixpans, a plusieurs objectifs :\n<ul>\n<li>faire de la veille concurrentielle sur les réseaux en s\'abonnant à différents flux</li>\n<li>créer des \"Social Walls\" en mettant en avant ses propres médias, dans des magasins par exemple</li>\n<li>animer sa communauté l\'incitant à poster avec un #hashtag particulier, et afficher les médias sur son site ou lors d\'événements</li>\n<li>créer des jeux-concours basés sur l\'écoute de #hashtags</li>\n</ul>\nIl s\'agit donc d\'un outil très flexible et particulièrement rapide à mettre en place.\n</p>\n<p>\nLes Liveboards peuvent également être intégrés en iframe sur n\'importe quel support, et dispose d\'une API pour récupérer directement le flux JSON et faire un affichage complètement personnalisé. Des Webhooks sont aussi disponibles pour un interfaçage de serveur à serveur en temps réel.\n</p>','Aggrégation et affichage de médias Facebook, Instagram et Twitter',NULL,'[1, 2, 3, 4, 5, 6, 8]','sixpans-liveboard-thumbnail.png','[\"sixpans-liveboard-desktop-1.png\", \"sixpans-liveboard-desktop-2.png\", \"sixpans-liveboard-desktop-3.png\", \"sixpans-liveboard-desktop-4.png\", \"sixpans-liveboard-desktop-5.png\", \"sixpans-liveboard-desktop-6.png\", \"sixpans-liveboard-desktop-7.png\", \"sixpans-liveboard-desktop-8.png\", \"sixpans-liveboard-desktop-9.png\", \"sixpans-liveboard-desktop-10.png\", \"sixpans-liveboard-desktop-11.png\", \"sixpans-liveboard-desktop-12.png\"]','sixpans',5,'2021-10-29 17:42:05'),
	(63,X'11EC39A7BED67F44B4DF25E613AA1F9A','Personnel','[\"Gameplay\"]','Thé pour Tango','<p>Au travers d\'une animation réalisée en stop motion, vivez la rencontre et l\'aventure d\'une théière et de sa future tasse.</p>\n<p>L\'animation se joue tant que la souris bouge. A l\'arrêt, l\'image se fige et les filtres (nouvelle fonctionnalité de Flash 8) sont utilisés pour modifier l\'aspect visuel des photos.</p>','Application développée dans le cadre du Master Médias Interactifs pour le module de photo interactive.',NULL,'[9]','perso-the-pour-tango-thumbnail.jpg','[\"perso-the-pour-tango-1.jpg\", \"perso-the-pour-tango-2.jpg\", \"perso-the-pour-tango-3.jpg\", \"perso-the-pour-tango-4.jpg\", \"perso-the-pour-tango-5.jpg\"]','perso',7,'2021-10-29 17:42:05'),
	(64,X'11EC39A7BED6D782B4DF25E613AA1F9A','Personnel','[\"Website\"]','Recto Verso','<p>Toutes les animations sont issues de la série.</p>\n<p>Graphisme réalisé par Pikigraphik.</p>','Site vitrine de la série animée Recto Verso.',NULL,'[9]','perso-recto-verso-thumbnail.jpg','[\"perso-recto-verso-1.jpg\", \"perso-recto-verso-2.jpg\", \"perso-recto-verso-3.jpg\", \"perso-recto-verso-4.jpg\", \"perso-recto-verso-5.jpg\"]','perso',4,'2021-10-29 17:42:05'),
	(65,X'11EC39A7BED70482B4DF25E613AA1F9A','Personnel','[\"Website\"]','Pikigraphik','<p>Portfolio interactif pouvant supporter tout type de contenu : photo, vidéo (hébergées sur le serveur ou Youtube, Dailymotion, etc...), gameplay Flash AS2 et AS3</p>','Site portfolio pour le studio Pikigraphik',NULL,'[9]','perso-pikigraphik-thumbnail.jpg','[\"perso-pikigraphik-1.jpg\", \"perso-pikigraphik-2.jpg\", \"perso-pikigraphik-3.jpg\", \"perso-pikigraphik-4.jpg\", \"perso-pikigraphik-5.jpg\"]','perso',5,'2021-10-29 17:42:05'),
	(66,X'11EC39A7BED7063AB4DF25E613AA1F9A','Personnel','[\"Gameplay\"]','Orthowave','<p>Application sous forme de logiciel pour PC et Mac à installer, véritable expérience de gameplay pédagogique.\nVersion multilingue, améliorée et optimisée du moteur de Lunald.</p>\n<p>Graphisme réalisé par <a href=\"https://www.charlesepinette.com/\" target=\"_blank\" rel=\"noopener\">Charles Epinette</a></p>','Manuel interactif du logiciel Orthowave.',NULL,'[9]','perso-orthowave-thumbnail.jpg','[\"perso-orthowave-1.jpg\", \"perso-orthowave-2.jpg\", \"perso-orthowave-3.jpg\", \"perso-orthowave-4.jpg\", \"perso-orthowave-5.jpg\", \"perso-orthowave-6.jpg\", \"perso-orthowave-7.jpg\"]','perso',1,'2021-10-29 17:42:05'),
	(67,X'11EC39A7BED70784B4DF25E613AA1F9A','Personnel','[\"Gameplay\"]','Lunald','<p>Un des premiers (si ce n\'est le premier) \"point & clic\" gratuit et online. Il est possible de sauvegarder à n\'importe quel moment de la partie, si un compte est créé.</p>\n<p>Graphisme réalisé par <a href=\"https://www.charlesepinette.com/\" target=\"_blank\" rel=\"noopener\">Charles Epinette</a></p>','Projet de fin d\'étude IUP IAISV.',NULL,'[9]','perso-lunald-thumbnail.jpg','[\"perso-lunald-1.jpg\", \"perso-lunald-2.jpg\", \"perso-lunald-3.jpg\", \"perso-lunald-4.jpg\", \"perso-lunald-5.jpg\", \"perso-lunald-6.jpg\"]','perso',3,'2021-10-29 17:42:05'),
	(68,X'11EC39A7BED70874B4DF25E613AA1F9A','Personnel','[\"Website\"]','Location Genin','<p>Réservation via un calendrier avec mise à jour en temps réél. La confirmation au client est faite par envoi de mail via le back office.</p>\n<p>Et, ce qui ne gâche rien, les appartements sont littéralement aux pieds des pistes !</p>\n<p>Graphisme réalisé par <a href=\"https://www.charlesepinette.com/\" target=\"_blank\" rel=\"noopener\">Charles Epinette</a></p>','Site de réservation en ligne d\'appartements aux Arcs 2000 pour Philippe Genin.',NULL,'[9, 11]','perso-genin-thumbnail.jpg','[\"perso-genin-1.jpg\", \"perso-genin-2.jpg\", \"perso-genin-3.jpg\", \"perso-genin-4.jpg\", \"perso-genin-5.jpg\"]','perso',2,'2021-10-29 17:42:05'),
	(69,X'11EC39A7BED70964B4DF25E613AA1F9A','Personnel','[\"Gameplay\"]','Granus','<p>Le système d\'armes est inspiré de la série Gradius, et un boss de fin de niveau vous attend pour en découdre !</p>\n<p>Les vidéos transparentes (nouvelle fonctionnalité de Flash 8) ont été utilisées pour les explosions, elles-même réalisées avec le logiciel Particle Illusion. Les éléments graphiques ont d\'abord été modélisés en 3D pour être intégrés par la suite en séquences PNG.</p>\n<p>Graphisme réalisé par <a href=\"https://www.charlesepinette.com/\" target=\"_blank\" rel=\"noopener\">Charles Epinette</a></p>','Gameplay de shoot\'em up réalisé dans le cadre du Master Médias Interactif, module programmation Flash.',NULL,'[9]','perso-granus-thumbnail.jpg','[\"perso-granus-1.jpg\", \"perso-granus-2.jpg\", \"perso-granus-3.jpg\", \"perso-granus-4.jpg\", \"perso-granus-5.jpg\", \"perso-granus-6.jpg\"]','perso',6,'2021-10-29 17:42:05'),
	(70,X'11EC39A7BED70AFEB4DF25E613AA1F9A','Personnel','[\"Gameplay\"]','Granny Fun House','<p>Mini-gameplay réalisé durant le développement de Lunald, pour la détente. Les éléments ont été réalisés sous 3DSMax puis intégrés dans Flash.</p>\n<p>Graphisme réalisé par <a href=\"https://www.charlesepinette.com/\" target=\"_blank\" rel=\"noopener\">Charles Epinette</a></p>','Stand de tir au pigeon sur le thème du 3ème âge.',NULL,'[9]','perso-granny-thumbnail.jpg','[\"perso-granny-1.jpg\", \"perso-granny-2.jpg\"]','perso',8,'2021-10-29 17:42:05'),
	(71,X'11EC39A7BED70BF8B4DF25E613AA1F9A','Personnel','[\"Dessin\"]','Modèle vivant',NULL,'Croquis réalisés dans le cadre de l\'ESAD (Ecole Supérieure d\'Art et de Design) d\'Amiens ou durant le module d\'Arts plastiques de l\'IUP IAISV.',NULL,'[12]','perso-modele-vivant-thumbnail.jpg','[\"perso-modele-vivant-1.jpg\", \"perso-modele-vivant-2.jpg\", \"perso-modele-vivant-3.jpg\", \"perso-modele-vivant-4.jpg\", \"perso-modele-vivant-5.jpg\", \"perso-modele-vivant-6.jpg\", \"perso-modele-vivant-7.jpg\", \"perso-modele-vivant-8.jpg\", \"perso-modele-vivant-9.jpg\", \"perso-modele-vivant-10.jpg\", \"perso-modele-vivant-11.jpg\", \"perso-modele-vivant-12.jpg\", \"perso-modele-vivant-13.jpg\", \"perso-modele-vivant-14.jpg\", \"perso-modele-vivant-15.jpg\", \"perso-modele-vivant-16.jpg\", \"perso-modele-vivant-17.jpg\", \"perso-modele-vivant-18.jpg\", \"perso-modele-vivant-19.jpg\", \"perso-modele-vivant-20.jpg\", \"perso-modele-vivant-21.jpg\"]','perso',9,'2021-10-29 17:42:05'),
	(72,X'11EC39A7BED71D8CB4DF25E613AA1F9A','Personnel','[\"Dessin\"]','Dessin originaux',NULL,'Croquis réalisés dans le cadre de l\'ESAD (Ecole Supérieure d\'Art et de Design) d\'Amiens, pour le module Scénographie de l\'IUP IAISV (création de costumes) ou simplement durant mon temps libre.',NULL,'[12]','perso-originaux-thumbnail.jpg','[\"perso-originaux-1.jpg\", \"perso-originaux-2.jpg\", \"perso-originaux-3.jpg\", \"perso-originaux-4.jpg\", \"perso-originaux-5.jpg\", \"perso-originaux-6.jpg\", \"perso-originaux-7.jpg\", \"perso-originaux-8.jpg\", \"perso-originaux-9.jpg\", \"perso-originaux-10.jpg\", \"perso-originaux-11.jpg\", \"perso-originaux-12.jpg\", \"perso-originaux-13.jpg\", \"perso-originaux-14.jpg\", \"perso-originaux-15.jpg\", \"perso-originaux-16.jpg\", \"perso-originaux-17.jpg\", \"perso-originaux-18.jpg\"]','perso',10,'2021-10-29 17:42:05'),
	(74,X'CC5464C63CBB11EC918AFB5EE45E27AB','BLZ Jeans','[\"Gameplay\", \"Instant Gagnant\"]','Le Boss du Casino','Sur le thème du casino, l\'application propose de choisir plusieurs amis (ou d\'en choisitr aléatoirement) pour les placer sur les cases d\'une roulette.\nSi la bille s\'arrête sur un des amis, c\'est gagné !','Application Facebook événementielle pour BLZ Jeans.',NULL,'[9, 10]','blz-casino-thumbnail.jpg','[\"blz-casino-1.png\", \"blz-casino-2.png\", \"blz-casino-3.png\", \"blz-casino-4.png\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(75,X'CC5723463CBB11EC918AFB5EE45E27AB','Carrefour','[\"Gameplay\", \"Instant Gagnant\"]','Spectacles','Mécanique de gain (grattage en Instant Gagnant) intégré dans le design de l\'application.','Opération événementielle pour Carrefour Spectacle.',NULL,'[9, 10]','carrefour-spectacle-thumbnail.jpg','[\"carrefour-spectacle-1.jpg\", \"carrefour-spectacle-2.jpg\", \"carrefour-spectacle-3.jpg\", \"carrefour-spectacle-4.jpg\", \"carrefour-spectacle-5.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(76,X'CC572A083CBB11EC918AFB5EE45E27AB','CHRU Montpellier','[\"Productivité\"]','Formulaire d\'admission','Une tablette est mise à disposition des patients qui peuvent remplir le formulaire d\'informations dans la salle d\'attente. Une fois le formulaire vérifié par le médecin, il est directement envoyé dans le SI de l\'hôpital.\nUn système de verrouillage de l\'application permet de garantir la confidentialité des informations.','WebApp de formulaire d\'admission au CHRU.',NULL,'[3, 4, 5, 11]','chru-montpellier-thumbnail.jpg','[\"chru-montpellier-1.png\", \"chru-montpellier-2.png\", \"chru-montpellier-3.png\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(77,X'CC572CD83CBB11EC918AFB5EE45E27AB','Connexion','[\"Gameplay\", \"Sweepstake\"]','Code Gagnant','Création d\'un framework PHP spécifique aux besoins de l\'application.\nPlusieurs milliers de codes à gérer par magasin, suivi en temps réel de la consommation des codes.','Opération promotionnelle pour les magasins Connexion.',NULL,'[9, 10]','connexion-code-gagnant-thumbnail.jpg','[\"connexion-code-gagnant-1.jpg\", \"connexion-code-gagnant-2.jpg\", \"connexion-code-gagnant-3.jpg\", \"connexion-code-gagnant-4.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(78,X'CC573C963CBB11EC918AFB5EE45E27AB','Connexion','[\"Gameplay\", \"Tirage Au Sort\"]','ConnexBall','Des questions qualifiantes sont proposées aux internautes entre deux sessions de casse-briques.\nCréation d\'un module de gameplay (casse-briques) pouvant être facilement déclinable selon les partenaires de Connexion.','Opération promotionnelle pour les magasins Connexion.\n\n\n',NULL,'[9, 10]','connexion-connexball-thumbnail.jpg','[\"connexion-connexball-1.jpg\", \"connexion-connexball-2.jpg\", \"connexion-connexball-3.jpg\", \"connexion-connexball-4.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(79,X'CC5775C63CBB11EC918AFB5EE45E27AB','Curly','[\"Quiz\"]','CurlyStars','Un test d\'affinité avec les mascottes est proposé à l\'internaute. L\'animation est assurée par les personnages modélisés en 3D puis intégrés dans l\'application par plus de 50 clips vidéos interactifs.\nAprès optimisation, l\'application passe sous les 10Mo sans temps de chargement intermédiaire.','Site avec vidéo interactive pour la marque Curly.',NULL,'[9, 10]','curly-curlystar-thumbnail.jpg','[\"curly-curlystar-1.png\", \"curly-curlystar-2.png\", \"curly-curlystar-3.png\", \"curly-curlystar-4.png\", \"curly-curlystar-5.png\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(80,X'CC5798BC3CBB11EC918AFB5EE45E27AB','Dickson','[\"Productivité\"]','Simulateur de store','Cette webApp vient en complément de l\'application DicksonDesigner. Elle aide le client à configurer son produit en s\'affranchissant des catalogues papier.\nPrise en charge de la connexion entre la webApp et les webservices de Dickson.','Webapp d\'aide à la vente de stores optimisée pour iPad.',NULL,'[3, 4, 5, 11]','dickson-simulateur-thumbnail.jpg','[\"dickson-simulateur-1.png\", \"dickson-simulateur-2.png\", \"dickson-simulateur-3.png\", \"dickson-simulateur-4.png\", \"dickson-simulateur-5.png\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(81,X'CC579A063CBB11EC918AFB5EE45E27AB','Ferrero','[\"Concours photo\"]','Ksting','Application accessible depuis un mini-site et une application Facebook dédiée pour plus de viralité et de visibilité.\nLes comptes sont partagés entre les deux versions.\nMise en place d\'un monitoring anti-fraude et analyse hebdomadaire des participations suspectes.','Jeu concours photo pour Ferrero.',NULL,'[9, 10]','ferrero-ksting-thumbnail.jpg','[\"ferrero-ksting-1.jpg\", \"ferrero-ksting-2.jpg\", \"ferrero-ksting-3.jpg\", \"ferrero-ksting-4.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(82,X'CC579BA03CBB11EC918AFB5EE45E27AB','Franprix','[\"Gameplay\"]','Magasin virtuel','La vue 3D gérée par Unity3d peut être couplée avec un site e-commerce ou une application Flash via une communication côté Javascript.\nLes produits mis en rayons sont gérés par un backoffice et chargés au runtime. Chaque magasin peut avoir sa propre configuration de rayon.','Prototype de virtualisation de magasin.',NULL,'[9, 11, 13]','franprix-magasin3d-thumbnail.jpg','[\"franprix-magasin3d-1.jpg\", \"franprix-magasin3d-2.jpg\", \"franprix-magasin3d-3.jpg\", \"franprix-magasin3d-4.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(83,X'CC57D6563CBB11EC918AFB5EE45E27AB','Kinepolis','[\"Gameplay\", \"Instant Gagnant\"]','Kinotes','Un quizz interactif permettait de masquer l\'ancien site à chaque réponse avec des post-it pour finalement révéler le nouveau.\nLes animations HTML ont été réalisées avec Edge Animate','Site événementiel pour les cinémas Kinepolis à l\'occasion de leur nouveau site.',NULL,'[3, 4, 5, 11]','kinepolis-kinotes-thumbnail.jpg','[\"kinepolis-kinotes-1.png\", \"kinepolis-kinotes-2.png\", \"kinepolis-kinotes-3.png\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(84,X'CC57FC6C3CBB11EC918AFB5EE45E27AB','KitKat','[\"Gameplay\", \"Instant Gagnant\"]','Break Ultime','<p>Tous les ans, un lot de 100 000€ était à gagner sous forme de voyage dans l\'espace, de séjour sur une île paradisiaque, de jet privé ou encore de 10 ans de vacances !</p>\n<p>Selon l\'opération, l\'application mettait en scène des vidéos interactives ou du gameplay arcade, sous forme d\'application mobile ou de webApp.</p>\n<p>Jusqu\'à 500 millions de codes imprimés sur les emballages de KitKat étaient à gérer en BDD, dans l\'environnement sécurisée de Nestlé. Opération multi-canal (web, SMS, webApp mobile), le compte multi-support était synchronisé et relié à la même BDD.</p>\n<p>Un monitoring anti-fraude était également mis en place, s\'adaptant aux nouvelles techniques de triche.</p>','Opération marketing annuelle de Nestlé pour sa marque KitKat.',NULL,'[9, 10]','kitkat-break-ultime-thumbnail.jpg','[\"kitkat-break-ultime-1.jpg\", \"kitkat-break-ultime-2.jpg\", \"kitkat-break-ultime-3.jpg\", \"kitkat-break-ultime-4.jpg\", \"kitkat-break-ultime-5.jpg\", \"kitkat-break-ultime-6.jpg\", \"kitkat-break-ultime-7.jpg\", \"kitkat-break-ultime-8.jpg\", \"kitkat-break-ultime-9.jpg\", \"kitkat-break-ultime-10.jpg\", \"kitkat-break-ultime-11.jpg\", \"kitkat-break-ultime-12.jpg\", \"kitkat-break-ultime-13.jpg\", \"kitkat-break-ultime-14.jpg\", \"kitkat-break-ultime-15.jpg\", \"kitkat-break-ultime-16.jpg\", \"kitkat-break-ultime-17.jpg\", \"kitkat-break-ultime-18.jpg\", \"kitkat-break-ultime-19.jpg\", \"kitkat-break-ultime-20.png\", \"kitkat-break-ultime-21.png\", \"kitkat-break-ultime-22.png\"]','featured',2,'2021-10-29 17:42:05'),
	(85,X'CC580DF63CBB11EC918AFB5EE45E27AB','LaRedoute','[\"Gameplay\", \"Highscore\"]','Magic Moments','Application en 5 langues avec 6 partenaires commerciaux (Oreange, Nestlé, Buch, Snapfish, DailyDeal, Oh!).\nGestion de la nature, des conditions d\'attibution et des modalités du gain à l\'issue du gameplay différentes pour chaque partenaire et/ou langue.','Gameplay shoot\'em up pour La Redoute International.',NULL,'[9, 10]','laredoute-magic-moments-thumbnail.jpg','[\"laredoute-magic-moments-1.jpg\", \"laredoute-magic-moments-2.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(86,X'CC580F4A3CBB11EC918AFB5EE45E27AB','LaRedoute','[\"Gameplay\"]','Saperlisapin','L\'application permet de planter des sapins dans une forêt virtuelle en y ajoutant un message personnel.\nLa forêt s\'agrandit automatiquement de manière concentrique suivant le nombre d\'arbres plantés via un algorithme.\nUn moteur de recherche permet de retrouver les sapins plantés.','Opération promotionelle pour LaRedoute.',NULL,'[9, 10]','laredoute-saperlisapin-thumbnail.jpg','[\"laredoute-saperlisapin-1.jpg\", \"laredoute-saperlisapin-2.jpg\", \"laredoute-saperlisapin-3.jpg\", \"laredoute-saperlisapin-4.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(87,X'CC5829583CBB11EC918AFB5EE45E27AB','Papermates','[\"Gameplay\"]','Matesworld','Le portail dispose d\'une chambre virtuelle customisable grâce à une boutique virtuelle.\nLa monnaie virtuelle se gagne en participant à la loterie quotidienne et aux différents mini-gameplays.\nLa plateforme accueille ponctuellement des jeux à dotations.\nRelais de news du site Gulli.fr via la rubrique dédiée et une application AIR.','Espace de jeux online et multilingue pour enfant.',NULL,'[9, 10]','papermate-matesworld-thumbnail.jpg','[\"papermate-matesworld-1.jpg\", \"papermate-matesworld-2.jpg\", \"papermate-matesworld-3.jpg\", \"papermate-matesworld-4.jpg\", \"papermate-matesworld-5.jpg\", \"papermate-matesworld-6.jpg\", \"papermate-matesworld-7.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(88,X'CC582AB63CBB11EC918AFB5EE45E27AB','Vediorbis','[\"Gameplay\"]','CDM Rugby','L\'application dispose de deux entrées, B2B et B2C, donnat droit à différents gains.\n6 gameplays arcade, débloqués au fil de la coupe du monde, sont à disposition pour gagner un maximum de points : jackpot, jeu de rythme, tir de pénalité, bonto, endurance (button mashing) et réflexe.','Site événementiel pour Vediorbis à l\'occasion de la coupe du monde de rugby.',NULL,'[9, 10]','vediorbis-rugby-thumbnail.jpg','[\"vediorbis-rugby-1.jpg\", \"vediorbis-rugby-2.jpg\", \"vediorbis-rugby-3.jpg\", \"vediorbis-rugby-4.jpg\", \"vediorbis-rugby-5.jpg\", \"vediorbis-rugby-6.jpg\", \"vediorbis-rugby-7.jpg\", \"vediorbis-rugby-8.jpg\"]',NULL,NULL,'2021-10-29 17:42:05'),
	(89,X'CC582BC43CBB11EC918AFB5EE45E27AB','Zôdio','[\"Concours photo\"]','Mon Noël avec Zôdio','Interface de modération en Flex.','Jeu concours photo pour Zôdio.',NULL,'[9, 10]','zodio-noel-thumbnail.jpg','[\"zodio-noel-1.jpg\", \"zodio-noel-2.jpg\", \"zodio-noel-3.jpg\", \"zodio-noel-4.jpg\", \"zodio-noel-5.jpg\"]',NULL,NULL,'2021-10-29 17:42:05');

/*!40000 ALTER TABLE `portfolio` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table technologies
# ------------------------------------------------------------

DROP TABLE IF EXISTS `technologies`;

CREATE TABLE `technologies` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `thumbnail` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOCK TABLES `technologies` WRITE;
/*!40000 ALTER TABLE `technologies` DISABLE KEYS */;

INSERT INTO `technologies` (`id`, `name`, `link`, `thumbnail`)
VALUES
	(1,'Node.js','https://nodejs.org/','nodejs.png'),
	(2,'MySQL','https://www.mysql.com/','mysql.png'),
	(3,'Javascript','https://developer.mozilla.org/fr/docs/Web/JavaScript','javascript.png'),
	(4,'HTML','https://developer.mozilla.org/fr/docs/Web/HTML','html.png'),
	(5,'CSS','https://developer.mozilla.org/fr/docs/Web/CSS','css.png'),
	(6,'Bootstrap','https://getbootstrap.com/','bootstrap.png'),
	(7,'Ember','https://emberjs.com/','ember.png'),
	(8,'jQuery','https://jquery.com/','jquery.png'),
	(9,'Flash','https://fr.wikipedia.org/wiki/Adobe_Flash_Player','flash.png'),
	(10,'SQL Server','https://www.microsoft.com/fr-fr/sql-server/sql-server-2019','sqlserver.png'),
	(11,'PHP','https://www.php.net/','php.png'),
	(12,'Dessin','https://fr.wikipedia.org/wiki/Crayon','pencil.png'),
	(13,'Unity','https://unity.com/fr','unity.png');

/*!40000 ALTER TABLE `technologies` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
